### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by ghost** [ekke/android-openssl-qt#7]
^
compilation terminated.
mem.c:59:19: fatal error: stdio.h: No such file or directory
 #include <stdio.h>
                   ^
compilation terminated.
mem_clr.c:60:20: fatal error: string.h: No such file or directory
 #include <string.h>
                    ^
compilation terminated.
mem_dbg.c:112:19: fatal error: stdio.h: No such file or directory
 #include <stdio.h>
                   ^
compilation terminated.
In file included from cversion.c:59:0:
cryptlib.h:62:21: fatal error: stdlib.h: No such file or directory
 # include <stdlib.h>
                     ^
compilation terminated.
In file included from ex_data.c:141:0:
cryptlib.h:62:21: fatal error: stdlib.h: No such file or directory
 # include <stdlib.h>
                     ^
compilation terminated.
cpt_err.c:62:19: fatal error: stdio.h: No such file or directory
 #include <stdio.h>
                   ^
compilation terminated.
In file included from uid.c:56:0:
../include/openssl/crypto.h:120:21: fatal error: stdlib.h: No such file or directory
 # include <stdlib.h>
                     ^
compilation terminated.
o_time.c:65:20: fatal error: string.h: No such file or directory
 #include <string.h>
                    ^
compilation terminated.
o_str.c:60:19: fatal error: ctype.h: No such file or directory
 #include <ctype.h>
                   ^
compilation terminated.
o_dir.c:60:19: fatal error: errno.h: No such file or directory
 #include <errno.h>
                   ^
compilation terminated.
In file included from o_fips.c:59:0:
cryptlib.h:62:21: fatal error: stdlib.h: No such file or directory
 # include <stdlib.h>
                     ^
compilation terminated.
In file included from o_init.c:56:0:
../e_os.h:468:28: fatal error: unistd.h: No such file or directory
 #    include OPENSSL_UNISTD
                            ^
compilation terminated.
make[1]: *** [local_depend] Error 1
make: *** [depend] Error 1

I am on MACOSX High sierra.

any Idea ?

**Comment by ekke** [comment]
seems you found the reason. perhaps you can leave a note if anyone else runs into this ?
thx

**Comment by ghost** [comment]
Resolution:
- You must execute command with sudo.

And in my case I have put OPENSSL_VERSION directly on build-all-arch.sh

**Comment by ekke** [comment]
thx for the info
