### ISSUE TITLE
clang: error: unknown argument: '-mandroid'

### ISSUE THREAD

**Issue by akontsevich** [ekke/android-openssl-qt#9]
I'm trying to run the script in Linux. My **NDK Version:** 18.1.5063045
```
export ANDROID_NDK_ROOT=~/Android/Sdk/ndk-bundle/
export OPENSSL_VERSION="openssl-1.0.2o"
./build-all-arch.sh
```
But got an error: 
```
make[1]: Entering directory '.../android-openssl-qt/openssl-1.0.2o/crypto'
clang: error: unknown argument: '-mandroid'
clang: error: unknown argument: '-mandroid'
make[1]: *** [Makefile:137: local_depend] Error 1
make[1]: Leaving directory '.../android-openssl-qt/openssl-1.0.2o/crypto'
make: *** [Makefile:484: depend] Error 1
```
Any chance to make it work in Linux or it works only under Mac? Script proposed on [qt.io](https://doc.qt.io/qt-5/android-openssl-support.html) a little bit tricky. Thanks!

**Comment by ekke** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;} AFAIK you should use NDK r10e for openssl even if you are using r18b for yor apps.                                                                                                                                                                           Von: notifications@github.comGesendet: 18. Dezember 2018 13:01An: android-openssl-qt@noreply.github.comAntworten: reply@reply.github.comCc: subscribed@noreply.github.comBetreff: [ekke/android-openssl-qt] clang: error: unknown argument: '-mandroid' (#9)  I'm trying to run the script in Linux. My NDK Version: 18.1.5063045
export ANDROID_NDK_ROOT=~/Android/Sdk/ndk-bundle/
export OPENSSL_VERSION="openssl-1.0.2o"
./build-all-arch.sh

But got an error:
make[1]: Entering directory '.../android-openssl-qt/openssl-1.0.2o/crypto'
clang: error: unknown argument: '-mandroid'
clang: error: unknown argument: '-mandroid'
make[1]: *** [Makefile:137: local_depend] Error 1
make[1]: Leaving directory '.../android-openssl-qt/openssl-1.0.2o/crypto'
make: *** [Makefile:484: depend] Error 1

Any chance to make it work in Linux or it works only under Mac? Script proposed on qt.io a little bit tricky. Thanks!

**Comment by akontsevich** [comment]
I see. Downloaded [android-ndk-r10e-linux-x86_64.zip](https://dl.google.com/android/repository/android-ndk-r15c-linux-x86_64.zip) - builds fine for `armeabi-v7a` and `x86`. 

- How to build for `arm64-v8a`?
- Also max Android API is `android-21` there. Is it ok or need to update this script later for greater versions?

**Comment by akontsevich** [comment]
Added `arm64-v8a` to the list in script: `archs=(arm64-v8a armeabi-v7a x86 x86_64)`, got error:
```
Error: Failed to find aarch64-linux-android-randlib. Please edit this script.
~/Android/Sdk/android-ndk-r10e/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/aarch64-linux-android-randlib

```
for both `r10e` and `r18b`. How to fix?

**Comment by akontsevich** [comment]
Found working script: https://github.com/couchbaselabs/couchbase-lite-libcrypto/issues/5 - works fine with any NDK. Will fork it.

**Comment by ekke** [comment]
thx. will wat5ch your fork and try next month.

**Comment by akontsevich** [comment]
https://github.com/akontsevich/openssl-android-build - fixed scripts

**Comment by udiakasnuke** [comment]
@akontsevich - Just wanted to confirm.. I am using your above repo for 1.0.2u version of openssl and looks like it works like a charm - i am able to create the libraries for arm64-v8a, armeabi-v7a and x86.

Do u have anything for 1.1.1i version ??

**Comment by ekke** [comment]
@udiakasnuke you should now use the KDAB project: https://github.com/KDAB/android_openssl 
I stopped developing on my project because of the great KDAB repo

**Comment by udiakasnuke** [comment]
@ekke - I came around this, but documentation is lacking in KDAB... I am not sure how to build openssl libraries for android using that. Can you please point me?? I need to build libraries for both 1.0.2u and 1.1.1i., but it still hope whatever i did using your project for 1.0.2u was right :) ... Thanks!!

**Comment by akontsevich** [comment]
> Do u have anything for 1.1.1i version ??

Change version in scripts to 1.1.1i - should work. I think README is clear enough there.

**Comment by udiakasnuke** [comment]
@akontsevich - Changing the version to 1.1.1i and running ./generate-headers-mac.sh resulted in
make: *** No rule to make target `clean'.  Stop.

looks like there is no makeFile.... Can i workaround this somehow?? please guide..

**Comment by akontsevich** [comment]
Sorry, won't help you on mac currently.

**Comment by udiakasnuke** [comment]
@akontsevich - :( .
Looks like the problem was in "make clean" since MakeFile is not present in 1.1.1i . But when i comment that even then its failing looks like this time its Configure command, openssl is asking me to choose some compiler.

Is there some other repo which i can follow along ?? Please suggest .

**Comment by akontsevich** [comment]
But why do You need it as recent Qt and QtC versions ship built-in openssl in installer?

**Comment by udiakasnuke** [comment]
eventually i need binaries and headers for 1.1.1i which i can use within my application..... but due to security reasons didn't want to integrate it directly.... Do you know or point me to someplace such that i can built it locally and then use?? Alternatively you said that these openssl binaries comes along with Qt, maybe i am not aware of that , how do i access those i.e 1.1.1i's ones. ??

**Comment by akontsevich** [comment]
Run [latest installer](https://www.qt.io/download-open-source) and You'll see:

![image](https://user-images.githubusercontent.com/3843657/103024762-20d26f80-4559-11eb-9c51-bc546ec87391.png)

I think You may find build scripts there as well.

**Comment by udiakasnuke** [comment]
<img width="972" alt="Screenshot 2020-12-23 at 11 39 40 PM" src="https://user-images.githubusercontent.com/4522895/103025646-3a36e400-4578-11eb-9e66-66837a392343.png">

Can't see any option for OpenSSL Toolkit!!

**Comment by akontsevich** [comment]
Then on mac it still missed.

**Comment by udiakasnuke** [comment]
@akontsevich - any workaround ?? please suggest. 
Your script worked fine for me for 1.0.2u but i need 1.1.1i as well.. anyway i can achieve . Can you point me to something?

**Comment by akontsevich** [comment]
Sorry, did not build 1.1 yet.

**Comment by udiakasnuke** [comment]
Looks like i am stuck now... need to migrate to 1.1.1.. but i am not able to find any proper documentation to do so :(
